In [3]:
import h5py
from utils.tools import SimpleImageViewer

In [4]:
h5_file_path = 'data/bedroom_04.h5'
h5_file      = h5py.File(h5_file_path, 'r')

In [7]:
h5_file['location'][()].shape[0]

408

In [8]:
h5_file['location'][5]

array([9.5, 0. ])

In [9]:
h5_file['location'][7]

array([9.5, 0. ])

In [15]:
h5_file['rotation'][3]

270

In [4]:
view = SimpleImageViewer()

In [10]:
view.imshow(h5_file['observation'][1])

In [17]:
h5_file['resnet_feature'][26][0]

array([0.02228752, 2.0556211 , 0.16012095, ..., 3.3870087 , 0.29483008,
       1.1944084 ], dtype=float32)

In [18]:
len(h5_file['resnet_feature'][26][0])

2048

In [15]:
len(h5_file['resnet_feature'][287])

10

In [27]:
import numpy as np

In [18]:
h5_file['resnet_feature'][287][0][:,np.newaxis]

array([[0.08918659],
       [1.9223003 ],
       [0.21887285],
       ...,
       [0.3097535 ],
       [0.43626192],
       [0.32121357]], dtype=float32)

In [19]:
h5_file['rotation'][287]

270

In [20]:
h5_file['rotation'][60]

0

In [22]:
h5_file['rotation'][286]

180

In [23]:
h5_file['rotation'][285]

90

In [24]:
h5_file['rotation'][284]

0

In [25]:
h5_file['location'][284]

array([8., 5.])

In [26]:
h5_file['location'][285]

array([8., 5.])

In [28]:
np.arange(5)

array([0, 1, 2, 3, 4])